import { publicPage } from './layout';

export function renderStudentPage(support = false): string {
    return publicPage({
        title: `${support ? 'Tira-dúvidas rápido' : 'Meu aprendizado'} | Obra Mais`,
        activePath: support ? '/tira-duvidas' : '/painel',
        extraStyles: `.student-shell{max-width:1180px;margin:auto;padding:40px 24px}.student-shell h1{font-size:clamp(28px,4vw,42px);letter-spacing:-.03em}.student-intro{color:#607086;line-height:1.6}.student-links{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}.student-links a,.student-shell button{padding:13px 20px;border:1px solid #dce4ee;border-radius:10px;background:white;color:#1267e8;font-weight:700;cursor:pointer}.student-shell button{background:#1267e8;color:white}.student-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:20px}.student-card{padding:24px;border:1px solid #dce4ee;border-radius:14px;background:white;box-shadow:0 5px 20px #10233f08}.student-card h2{font-size:20px;margin-top:0}.student-card p{line-height:1.6;color:#607086}.student-card a{color:#1267e8;font-weight:700}.student-card progress{width:100%;accent-color:#149c60}.student-shell label{display:grid;gap:8px;margin-bottom:18px;font-weight:600}.student-shell input,.student-shell textarea{padding:14px;border:1px solid #cbd5e1;border-radius:9px;width:100%;font:inherit}.student-shell textarea{min-height:140px}.student-shell button:disabled{opacity:.6}.student-status{padding:12px 0;line-height:1.5}.student-card time{font-size:13px;color:#607086}`,
        body: `<main class="student-shell"><p class="eyebrow">SEU ESPAÇO PARA APRENDER</p><h1>${support ? 'Tira-dúvidas rápido' : 'Meu aprendizado'}</h1><p class="student-intro">${support ? 'Descreva sua dúvida e acompanhe as perguntas que você enviou.' : 'Continue seus cursos, acompanhe sua evolução e conquiste seu próximo certificado.'}</p><nav class="student-links" aria-label="Área do aluno"><a href="/painel">Meu aprendizado</a><a href="/cursos">Explorar cursos</a><a href="/certificados">Certificados</a><a href="/tira-duvidas">Tira-dúvidas</a></nav>
        ${support ? `<form id="question-form" class="student-card"><h2>Qual é a sua dúvida?</h2><label for="question-title">Assunto<input id="question-title" name="title" maxlength="160" required placeholder="Ex.: Onde encontro as aulas do meu curso?"></label><label for="question-description">Conte um pouco mais<textarea id="question-description" name="description" maxlength="5000" required></textarea></label><p class="student-intro">Sua pergunta será registrada para acompanhamento. Este espaço não oferece resposta automática.</p><button type="submit">Enviar dúvida</button><p id="send-status" role="status" aria-live="polite"></p></form><h2>Minhas dúvidas</h2>` : '<h2>Continue de onde parou</h2>'}
        <p class="student-status" id="student-status" role="status" aria-live="polite">Carregando...</p><div class="student-grid" id="student-items"></div></main><script src="/student.js" defer></script>`,
    });
}
